yourName = input("What's your name?: ")
favoriteFood = input("What's your favorite food?: ")
favoriteMusic = input("What's your favorite music?: ")
yourFrom = input("Where do you live?: ")
print("Getting to know you!")
input("You are")
input(yourName)
input("You're probably hungry for")
input(favoriteFood)
input("and you're definitely getting your groove on to")
input(favoriteMusic)
input("living in the amazing")
input(yourFrom)
input("Yeah! :)")